### ISSUE TITLE
spinner disappears :- minimize the app, then comes back to foreground.

### ISSUE THREAD

**Issue by MiteshiOS** [saru2020/SARMaterialDesignSpinner#3]
If i enter in background and then come back to foreground the spinner is automatically disappears.

steps :-
- Run demo app
- spinner is animating
- press home button(Or keep app into background)
- again come back to foreground 
- see Spinner is disappear.

**Comment by saru2020** [comment]
It is the default behavior followed by Apple for CAAnimations. 
CAAnimations are stopped and removed when the app is backgrounded. 

**My Suggestion:** Pause/Stop the animation when the app is backgrounded by either listening to the UIApplicationDidEnterBackgroundNotification or by handling the callback from the AppDelegate, and then play again when the app is foregrounded.

Have replicated/demonstrated the same in the sample app.

Hope it helps!
